# **************************
# * Stage 1: Constructor (Builder)
# **************************
FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./

# Installing dependencies
RUN npm ci

# **************************
# * Stage 2: Runner (Final)
# **************************
FROM node:20-bookworm-slim

WORKDIR /app

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npm install -g @playwright/test && \
    npx playwright install-deps chromium && \
    npx playwright install chromium

COPY --from=build /app/node_modules ./node_modules
COPY . .

CMD ["npx", "playwright", "test"]