apiVersion: v1
kind: Pod
metadata:
  name: playwright-runner-pod-kubernetes
spec:
  containers:
  - name: test-container-playwright
    image: my-playwright:v1
    imagePullPolicy: Never
    command: ["npx", "playwright", "test"]
  restartPolicy: Never