apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

nameSuffix: -prod

commonLabels:
  environment: production

images:
  - name: playwright:latest
    newName: ghcr.io/andres4715-gif/playwright_docker_ci-cd_example
    newTag: v1.0-stable

configMapGenerator:
  - name: config-app-vi
    behavior: merge
    literals:
      - database_host="10.0.0.5"
      - nivel_log="error"