apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mis-tests-playwright
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/andres4715-gif/playwright_Docker_CI-CD_example.git'
    targetRevision: HEAD
    path: ./manifest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  # Magic synchronisation 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
