apiVersion: v1
kind: Pod
metadata:
  name: playwright-runner
spec:
  containers:
  - name: test-container
    image: mis-tests:v1
    imagePullPolicy: Never
    command: ["npx", "playwright", "test"]
  restartPolicy: Never