name: publish Docker image into GitHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Define the image name it manages all the lowercase name of the image
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write 

    steps:
      - name: pull code
        uses: actions/checkout@v4

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # if the event is push in the master branch, add 'latest'
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            # Use the sha of the commit (for the history)
            type=sha
            # if the pull request is a PR, use the PR number (ej: pr-2)
            type=ref,event=pr
            # if the event is a normal branch, use the branch name
            type=ref,event=branch

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 3. Use the output of the `meta` step as inputs
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update helm chart with a new image
        # Just run it if we are in  master/main, not in Pull Requests
        if: github.ref == 'refs/heads/master'
        run: |
          # 1. Install yq editor of command line
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          
          # 2. Github bot configuration
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 3. Define the exact TAG (the short SHA that use docker metadata)
          NEW_TAG="sha-$(git rev-parse --short HEAD)"
          echo "Updating values.yaml using tag: $NEW_TAG"
          
          # 4. Edit file values.yaml (magic)
          # This search .image.tag and it change it without broke the format
          yq -i ".image.tag = \"$NEW_TAG\"" playwright-chart/values.yaml
          
          # 5. setup and push changes
          # Note(Important): "[skip ci]" in vital for this commit does not launch the workflow again (avoid infinity loop)
          git add playwright-chart/values.yaml
          git commit -m "chore(helm): update image tag to $NEW_TAG [skip ci]"
          git push