name: publish Docker image into GitHub

on:
  push:
    branches: [ "master" ]

# env configuration
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write 

    steps:
      - name: pull code
        uses: actions/checkout@v4

      - name: Repository name to lowercase
        run: |
              echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # This is the token used to push the image
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Here you will see the image.
          # 1. 'latest': for latest version
          # 2. 'sha': for history
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}